# Generated by Django 5.2.4 on 2025-08-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
